"""
HTML Dashboard Generator.
Creates a styled HTML report for the S3 dashboard.
"""

from scoring.calculator import get_score_grade


def generate_html_dashboard(report):
    """Generate a full HTML dashboard report."""
    scan_date = report["scan_date"]
    summary = report["summary"]

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CloudSentry Report - {scan_date}</title>
<style>
"""
    html += get_css()
    html += f"""
</style>
</head>
<body>
<div class="container">
<header>
<h1>CloudSentry Report</h1>
<p class="date">{scan_date}</p>
</header>
"""

    # Summary cards
    sev = summary["severity"]
    html += f"""
<div class="summary-cards">
<div class="card">
<span class="card-number">{summary['total_accounts']}</span>
<span class="card-label">Accounts</span>
</div>
<div class="card critical">
<span class="card-number">{sev['critical']}</span>
<span class="card-label">Critical</span>
</div>
<div class="card high">
<span class="card-number">{sev['high']}</span>
<span class="card-label">High</span>
</div>
<div class="card medium">
<span class="card-number">{sev['medium']}</span>
<span class="card-label">Medium</span>
</div>
<div class="card low">
<span class="card-number">{sev['low']}</span>
<span class="card-label">Low</span>
</div>
</div>
"""

    # Per-account sections
    for acct in report["accounts"]:
        html += render_account_section(acct)

    html += """
<footer>
<p>Generated by <a href="https://github.com/durrello/cloudsentry">CloudSentry</a></p>
</footer>
</div>
</body>
</html>"""

    return html


def render_account_section(acct):
    """Render a single account's report section."""
    grade = get_score_grade(acct["score"])
    trend_html = ""
    if acct["score_change"] is not None:
        color = "#22c55e" if acct["score_change"] > 0 else "#ef4444"
        arrow = "+" if acct["score_change"] >= 0 else ""
        trend_html = f' <span style="color:{color}">({arrow}{acct["score_change"]})</span>'

    html = f"""
<section class="account">
<h2>{acct['name']} <span class="account-id">({acct['account_id']})</span></h2>

<div class="score-section">
<div class="score-circle grade-{grade.lower()}">{acct['score']}</div>
<div class="score-meta">
<span class="grade">Grade: {grade}{trend_html}</span>
<span class="regions">Regions: {', '.join(acct['regions'])}</span>
</div>
</div>
"""

    # Cost section
    cost = acct.get("cost", {})
    if cost.get("month_to_date") or cost.get("last_month"):
        html += f"""
<div class="section">
<h3>Cost</h3>
<table>
<tr><td>Month-to-date</td><td>${cost.get('month_to_date', 0):.2f}</td></tr>
<tr><td>Forecast (end of month)</td><td>${cost.get('forecast', 0):.2f}</td></tr>
<tr><td>Last month total</td><td>${cost.get('last_month', 0):.2f}</td></tr>
</table>
"""
        # Burn rate
        burn = cost.get("burn_rate", {})
        if burn.get("daily_rate", 0) > 0:
            html += f"""
<h4 style="color:#94a3b8;margin-top:12px;">Burn Rate</h4>
<table>
<tr><td>Daily rate</td><td>${burn['daily_rate']:.2f}/day</td></tr>
<tr><td>Monthly rate (current)</td><td>${burn['monthly_rate']:.2f}/month</td></tr>
<tr><td>Annual rate (current)</td><td>${burn['annual_rate']:.2f}/year</td></tr>
"""
            if burn.get("potential_monthly_savings", 0) > 0:
                html += f"""<tr><td>Potential savings (if all fixes applied)</td><td style="color:#4ade80">-${burn['potential_monthly_savings']:.2f}/month</td></tr>
<tr><td>Optimized monthly rate</td><td style="color:#4ade80">${burn['optimized_monthly_rate']:.2f}/month</td></tr>
<tr><td>Optimized annual rate</td><td style="color:#4ade80">${burn['optimized_annual_rate']:.2f}/year</td></tr>
"""
            html += "</table>"

        # Credits
        credits = cost.get("credits", {})
        if credits.get("has_credits"):
            html += f"""
<h4 style="color:#94a3b8;margin-top:12px;">Credits</h4>
<table>
<tr><td>Credits used (this year)</td><td>${credits.get('total_credits', 0):.2f}</td></tr>
"""
            if burn.get("days_until_credits_expire") is not None:
                html += f"<tr><td>Estimated days until credits run out</td><td>{burn['days_until_credits_expire']} days</td></tr>"
            html += "</table>"

        html += "</div>"

    # Findings
    findings = acct.get("findings", [])
    if findings:
        html += '<div class="section"><h3>Findings</h3><table class="findings-table">'
        html += '<tr><th>Severity</th><th>Finding</th><th>Resource</th><th>Region</th></tr>'
        for f in sorted(findings, key=lambda x: {"critical": 0, "high": 1, "medium": 2, "low": 3}.get(x["severity"], 4)):
            sev_class = f["severity"]
            html += f'<tr class="{sev_class}"><td><span class="badge {sev_class}">{f["severity"].upper()}</span></td>'
            html += f'<td>{f["title"]}</td><td>{f.get("resource_id", "")}</td><td>{f.get("region", "")}</td></tr>'
        html += '</table></div>'

    # Violations
    violations = acct.get("violations", [])
    if violations:
        html += '<div class="section"><h3>Policy Violations</h3><table class="findings-table">'
        html += '<tr><th>Severity</th><th>Category</th><th>Violation</th><th>Resource</th></tr>'
        for v in sorted(violations, key=lambda x: {"critical": 0, "high": 1, "medium": 2, "low": 3}.get(x["severity"], 4)):
            html += f'<tr><td><span class="badge {v["severity"]}">{v["severity"].upper()}</span></td>'
            html += f'<td>{v.get("category", "")}</td><td>{v["title"]}</td><td>{v.get("resource_id", "")}</td></tr>'
        html += '</table></div>'

    html += '</section>'
    return html


def get_css():
    """Return the CSS for the dashboard."""
    return """
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f172a; color: #e2e8f0; line-height: 1.6; }
.container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
header { text-align: center; margin-bottom: 2rem; }
header h1 { font-size: 2rem; color: #f8fafc; }
.date { color: #94a3b8; font-size: 1.1rem; }
.summary-cards { display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; }
.card { flex: 1; min-width: 100px; background: #1e293b; border-radius: 8px; padding: 1rem; text-align: center; border: 1px solid #334155; }
.card-number { display: block; font-size: 2rem; font-weight: bold; color: #f8fafc; }
.card-label { color: #94a3b8; font-size: 0.85rem; }
.card.critical { border-color: #ef4444; }
.card.critical .card-number { color: #ef4444; }
.card.high { border-color: #f97316; }
.card.high .card-number { color: #f97316; }
.card.medium { border-color: #eab308; }
.card.medium .card-number { color: #eab308; }
.card.low { border-color: #64748b; }
.account { background: #1e293b; border-radius: 12px; padding: 1.5rem; margin-bottom: 2rem; border: 1px solid #334155; }
.account h2 { color: #f8fafc; margin-bottom: 1rem; }
.account-id { color: #64748b; font-size: 0.85rem; font-weight: normal; }
.score-section { display: flex; align-items: center; gap: 1.5rem; margin-bottom: 1.5rem; }
.score-circle { width: 80px; height: 80px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 1.5rem; font-weight: bold; }
.grade-a { background: #166534; color: #4ade80; }
.grade-b { background: #1a5e1f; color: #86efac; }
.grade-c { background: #854d0e; color: #fde047; }
.grade-d { background: #9a3412; color: #fdba74; }
.grade-f { background: #7f1d1d; color: #fca5a5; }
.score-meta { display: flex; flex-direction: column; }
.grade { font-size: 1.1rem; color: #f8fafc; }
.regions { color: #94a3b8; font-size: 0.85rem; }
.section { margin-top: 1.5rem; }
.section h3 { color: #cbd5e1; margin-bottom: 0.5rem; }
table { width: 100%; border-collapse: collapse; }
td, th { padding: 0.5rem; text-align: left; border-bottom: 1px solid #334155; }
th { color: #94a3b8; font-weight: 500; }
.findings-table { font-size: 0.85rem; }
.badge { padding: 2px 8px; border-radius: 4px; font-size: 0.7rem; font-weight: bold; }
.badge.critical { background: #7f1d1d; color: #fca5a5; }
.badge.high { background: #7c2d12; color: #fdba74; }
.badge.medium { background: #713f12; color: #fde047; }
.badge.low { background: #1e293b; color: #94a3b8; border: 1px solid #475569; }
footer { text-align: center; margin-top: 2rem; color: #64748b; }
footer a { color: #60a5fa; text-decoration: none; }
"""
